export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'

export interface OperationField {
  name: string
  label: string
  placeholder?: string
}

export interface ApiOperation {
  id: string
  domain: string
  title: string
  method: HttpMethod
  path: string
  auth?: boolean
  pathParams?: OperationField[]
  queryParams?: OperationField[]
  bodyTemplate?: unknown
  operationKind?: OperationKind
  dangerLevel?: OperationDangerLevel
  resultView?: OperationResultView
  assistantEligible?: boolean
  requiresEntityContext?: boolean
  metadata?: Record<string, unknown>
}

export type OperationKind = 'direct' | 'contextual' | 'agent_assisted' | 'admin'
export type OperationDangerLevel = 'low' | 'medium' | 'high'
export type OperationResultView = 'summary' | 'list' | 'detail' | 'audit'

export interface OperationProfile {
  kind: OperationKind
  dangerLevel: OperationDangerLevel
  resultView: OperationResultView
  assistantEligible: boolean
  requiresEntityContext: boolean
  humanReady: boolean
}

const agentSignals = [
  'ai',
  'agent',
  'assistant',
  'analyze',
  'analysis',
  'match',
  'estimate',
  'classify',
  'compute',
  'sync',
  'recommend',
]

const adminSignals = [
  'identity',
  'provider',
  'channel',
  'routing-rule',
  'governance',
  'observability',
  'verification',
  'tool',
  'trace',
  'metric',
  'layer',
]

function includesAny(value: string, signals: string[]): boolean {
  return signals.some((signal) => value.includes(signal))
}

export function getOperationProfile(operation: ApiOperation): OperationProfile {
  const searchable = `${operation.id} ${operation.domain} ${operation.path} ${operation.title}`.toLowerCase()
  const requiresEntityContext = operation.requiresEntityContext ?? ((operation.pathParams?.length ?? 0) > 0)
  const assistantEligible = operation.assistantEligible ?? includesAny(searchable, agentSignals)
  const isAdmin = includesAny(searchable, adminSignals)
  const isDelete = operation.method === 'DELETE'
  const isMutation = operation.method !== 'GET'
  const dangerLevel = operation.dangerLevel ?? (isDelete ? 'high' : isMutation || requiresEntityContext ? 'medium' : 'low')
  const kind =
    operation.operationKind ??
    (assistantEligible ? 'agent_assisted' : isAdmin ? 'admin' : requiresEntityContext ? 'contextual' : 'direct')
  const resultView =
    operation.resultView ??
    (operation.method === 'GET'
      ? operation.id.includes('list') || operation.path.endsWith('s')
        ? 'list'
        : 'detail'
      : isAdmin || searchable.includes('log') || searchable.includes('audit')
        ? 'audit'
        : 'summary')

  return {
    kind,
    dangerLevel,
    resultView,
    assistantEligible,
    requiresEntityContext,
    humanReady: !requiresEntityContext || kind === 'direct' || operation.method === 'GET',
  }
}

const allApiOperations: ApiOperation[] = [
  {
    id: 'erp-catalog',
    domain: 'ERP',
    title: 'operation.erp.catalog',
    method: 'GET',
    path: '/erp/catalog',
    resultView: 'list',
  },
  {
    id: 'erp-record-list',
    domain: 'ERP',
    title: 'operation.erp.recordList',
    method: 'GET',
    path: '/erp/{tableCode}',
    pathParams: [{ name: 'tableCode', label: 'operation.erp.tableCode', placeholder: 'MCRD' }],
    queryParams: [{ name: 'limit', label: 'operation.param.limit', placeholder: '100' }],
    resultView: 'list',
  },
  {
    id: 'erp-record-create',
    domain: 'ERP',
    title: 'operation.erp.recordCreate',
    method: 'POST',
    path: '/erp/{tableCode}',
    pathParams: [{ name: 'tableCode', label: 'operation.erp.tableCode', placeholder: 'MCRD' }],
    bodyTemplate: {
      key: 'C0001',
      data: {
        CardCode: 'C0001',
        CardName: 'Acme Customer',
        CardType: 'C',
      },
    },
    resultView: 'detail',
  },
  {
    id: 'erp-record-get',
    domain: 'ERP',
    title: 'operation.erp.recordGet',
    method: 'GET',
    path: '/erp/{tableCode}/{key}',
    pathParams: [
      { name: 'tableCode', label: 'operation.erp.tableCode', placeholder: 'MCRD' },
      { name: 'key', label: 'operation.erp.recordKey', placeholder: 'C0001' },
    ],
    resultView: 'detail',
  },
  {
    id: 'erp-record-update',
    domain: 'ERP',
    title: 'operation.erp.recordUpdate',
    method: 'PATCH',
    path: '/erp/{tableCode}/{key}',
    pathParams: [
      { name: 'tableCode', label: 'operation.erp.tableCode', placeholder: 'MCRD' },
      { name: 'key', label: 'operation.erp.recordKey', placeholder: 'C0001' },
    ],
    bodyTemplate: {
      data: {
        CardName: 'Updated Customer',
      },
    },
    resultView: 'detail',
  },
  {
    id: 'erp-child-list',
    domain: 'ERP',
    title: 'operation.erp.childList',
    method: 'GET',
    path: '/erp/{tableCode}/{key}/{childCode}',
    pathParams: [
      { name: 'tableCode', label: 'operation.erp.tableCode', placeholder: 'MINV' },
      { name: 'key', label: 'operation.erp.recordKey', placeholder: '1001' },
      { name: 'childCode', label: 'operation.erp.childTableCode', placeholder: 'INV1' },
    ],
    queryParams: [{ name: 'limit', label: 'operation.param.limit', placeholder: '100' }],
    resultView: 'list',
  },
  {
    id: 'erp-child-create',
    domain: 'ERP',
    title: 'operation.erp.childCreate',
    method: 'POST',
    path: '/erp/{tableCode}/{key}/{childCode}',
    pathParams: [
      { name: 'tableCode', label: 'operation.erp.tableCode', placeholder: 'MINV' },
      { name: 'key', label: 'operation.erp.recordKey', placeholder: '1001' },
      { name: 'childCode', label: 'operation.erp.childTableCode', placeholder: 'INV1' },
    ],
    bodyTemplate: {
      key: '1',
      data: {
        LineNum: 1,
        LineStatus: 'O',
        Payload: {
          ItemCode: 'A-100',
          Quantity: 1,
        },
      },
    },
    resultView: 'detail',
  },
  {
    id: 'erp-action-list',
    domain: 'ERP',
    title: 'operation.erp.actions',
    method: 'GET',
    path: '/erp/actions',
    resultView: 'list',
    assistantEligible: true,
  },
  {
    id: 'erp-mreq-approve-action',
    domain: 'Project',
    title: 'operation.erp.MREQ.approve',
    method: 'POST',
    path: '/erp/MREQ/{ReqCode}/actions/approve',
    pathParams: [{ name: 'ReqCode', label: 'operation.erp.ReqCode', placeholder: 'REQ-1001' }],
    bodyTemplate: { data: { approver: '' } },
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mreq-convert-action',
    domain: 'Project',
    title: 'operation.erp.MREQ.convert',
    method: 'POST',
    path: '/erp/MREQ/{ReqCode}/actions/convert-to-project',
    pathParams: [{ name: 'ReqCode', label: 'operation.erp.ReqCode', placeholder: 'REQ-1001' }],
    bodyTemplate: { data: { PrjCode: 'PRJ-1001' } },
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mprj-refresh-cost-action',
    domain: 'Project',
    title: 'operation.erp.MPRJ.refreshCost',
    method: 'POST',
    path: '/erp/MPRJ/{PrjCode}/actions/refresh-cost',
    pathParams: [{ name: 'PrjCode', label: 'operation.erp.PrjCode', placeholder: 'PRJ-1001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mprj-close-feedback-action',
    domain: 'Project',
    title: 'operation.erp.MPRJ.closeFeedback',
    method: 'POST',
    path: '/erp/MPRJ/{PrjCode}/actions/close-feedback',
    pathParams: [{ name: 'PrjCode', label: 'operation.erp.PrjCode', placeholder: 'PRJ-1001' }],
    bodyTemplate: { data: { result: 'accepted' } },
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mpor-submit-action',
    domain: 'Procurement',
    title: 'operation.erp.MPOR.submit',
    method: 'POST',
    path: '/erp/MPOR/{DocEntry}/actions/submit',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '1001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mpor-approve-action',
    domain: 'Procurement',
    title: 'operation.erp.MPOR.approve',
    method: 'POST',
    path: '/erp/MPOR/{DocEntry}/actions/approve',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '1001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mpdn-post-action',
    domain: 'Procurement',
    title: 'operation.erp.MPDN.post',
    method: 'POST',
    path: '/erp/MPDN/{DocEntry}/actions/post',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '2001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mrdr-confirm-action',
    domain: 'Sales',
    title: 'operation.erp.MRDR.confirm',
    method: 'POST',
    path: '/erp/MRDR/{DocEntry}/actions/confirm',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '3001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mrdr-approve-action',
    domain: 'Sales',
    title: 'operation.erp.MRDR.approve',
    method: 'POST',
    path: '/erp/MRDR/{DocEntry}/actions/approve',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '3001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mdln-post-action',
    domain: 'Sales',
    title: 'operation.erp.MDLN.post',
    method: 'POST',
    path: '/erp/MDLN/{DocEntry}/actions/post',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '4001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-minv-post-action',
    domain: 'FinanceReceivables',
    title: 'operation.erp.MINV.post',
    method: 'POST',
    path: '/erp/MINV/{DocEntry}/actions/post',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '5001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mrct-allocate-action',
    domain: 'FinanceReceivables',
    title: 'operation.erp.MRCT.allocate',
    method: 'POST',
    path: '/erp/MRCT/{DocEntry}/actions/allocate',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '6001' }],
    bodyTemplate: { data: { TargetTable: 'MINV', TargetKey: '5001', Amount: 100 } },
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mign-post-action',
    domain: 'Inventory',
    title: 'operation.erp.MIGN.post',
    method: 'POST',
    path: '/erp/MIGN/{DocEntry}/actions/post',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '7001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mige-post-action',
    domain: 'Inventory',
    title: 'operation.erp.MIGE.post',
    method: 'POST',
    path: '/erp/MIGE/{DocEntry}/actions/post',
    pathParams: [{ name: 'DocEntry', label: 'operation.erp.DocEntry', placeholder: '8001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'erp-mjdt-post-action',
    domain: 'FinanceAccounting',
    title: 'operation.erp.MJDT.post',
    method: 'POST',
    path: '/erp/MJDT/{TransId}/actions/post',
    pathParams: [{ name: 'TransId', label: 'operation.erp.TransId', placeholder: '9001' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
    resultView: 'summary',
    assistantEligible: true,
  },
  {
    id: 'system-health',
    domain: 'Dashboard',
    title: '健康检查',
    method: 'GET',
    path: '/health',
    auth: false,
  },
  {
    id: 'dashboard-overview',
    domain: 'Dashboard',
    title: '系统总览',
    method: 'GET',
    path: '/dashboard/overview',
  },
  {
    id: 'identity-list-roles',
    domain: 'Identity',
    title: '角色列表',
    method: 'GET',
    path: '/roles',
    auth: false,
  },
  {
    id: 'identity-register-agent',
    domain: 'Identity',
    title: '注册 AI Agent',
    method: 'POST',
    path: '/agents/register',
    bodyTemplate: {
      name: 'Finance Analyst Agent',
      model_type: 'gpt-4.1',
      capabilities: ['analysis', 'reporting'],
      permission_level: 'L2',
      agent_origin: 'internal',
      provider: 'OpenAI',
      service_class: 'model',
      vendor: '',
      contract_ref: '',
      risk_level: 'medium',
      metadata: {},
    },
  },
  {
    id: 'identity-list-agents',
    domain: 'Identity',
    title: 'Agent 列表',
    method: 'GET',
    path: '/agents',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'identity-agent-auth',
    domain: 'Identity',
    title: 'Agent 鉴权',
    method: 'POST',
    path: '/agents/auth',
    auth: false,
    bodyTemplate: {
      agent_id: '',
      api_key: '',
    },
  },
  {
    id: 'organization-create',
    domain: 'SystemAdmin',
    title: '平台创建组织档案',
    method: 'POST',
    path: '/platform/admin/organizations',
    bodyTemplate: {
      name: 'Meta-Org',
      description: 'AI-native organization operating platform',
    },
  },
  {
    id: 'organization-list',
    domain: 'SystemAdmin',
    title: '平台组织列表',
    method: 'GET',
    path: '/platform/organizations',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'organization-current',
    domain: 'Organization',
    title: '当前组织',
    method: 'GET',
    path: '/organization/current',
  },
  {
    id: 'organization-get',
    domain: 'SystemAdmin',
    title: '平台组织详情',
    method: 'GET',
    path: '/platform/admin/organizations/{id}',
    pathParams: [{ name: 'id', label: '组织 ID' }],
  },
  {
    id: 'organization-update',
    domain: 'SystemAdmin',
    title: '修改平台组织档案',
    method: 'PATCH',
    path: '/platform/admin/organizations/{id}',
    pathParams: [{ name: 'id', label: '组织 ID' }],
    bodyTemplate: {
      name: 'Meta-Org',
      description: 'Updated organization profile',
    },
  },
  {
    id: 'system-admin-schema-change-verify',
    domain: 'SystemAdmin',
    title: 'operation.systemAdmin.schemaChangeVerify',
    method: 'POST',
    path: '/platform/admin/schema-change-requests/{id}/verify',
    pathParams: [{ name: 'id', label: 'operation.systemAdmin.schemaChangeRequestId' }],
    operationKind: 'admin',
    dangerLevel: 'low',
    resultView: 'audit',
  },
  {
    id: 'department-create',
    domain: 'Organization',
    title: '创建部门',
    method: 'POST',
    path: '/organizations/{id}/departments',
    pathParams: [{ name: 'id', label: '组织 ID' }],
    bodyTemplate: {
      name: 'Product Engineering',
      code: 'ENG',
      description: 'Product and platform engineering',
      status: 'active',
      sort_order: 10,
      parent_id: null,
      metadata: {},
    },
  },
  {
    id: 'department-list',
    domain: 'Organization',
    title: '部门列表',
    method: 'GET',
    path: '/organizations/{id}/departments',
    pathParams: [{ name: 'id', label: '组织 ID' }],
  },
  {
    id: 'department-tree',
    domain: 'Organization',
    title: '部门树',
    method: 'GET',
    path: '/organizations/{id}/departments/tree',
    pathParams: [{ name: 'id', label: '组织 ID' }],
  },
  {
    id: 'department-get',
    domain: 'Organization',
    title: '部门详情',
    method: 'GET',
    path: '/departments/{id}',
    pathParams: [{ name: 'id', label: '部门 ID' }],
  },
  {
    id: 'department-update',
    domain: 'Organization',
    title: '更新部门',
    method: 'PATCH',
    path: '/departments/{id}',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    bodyTemplate: {
      name: 'Product Engineering',
      description: 'Updated department profile',
      status: 'active',
      sort_order: 20,
      metadata: {},
    },
  },
  {
    id: 'position-create',
    domain: 'Organization',
    title: '创建岗位',
    method: 'POST',
    path: '/departments/{id}/positions',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    bodyTemplate: {
      name: 'Workflow Owner',
      code: 'WF_OWNER',
      description: 'Own workflow planning and node accountability',
      permission_level: 'L2',
      required_capabilities: ['planning', 'review'],
      status: 'active',
      sort_order: 10,
      metadata: {},
    },
  },
  {
    id: 'position-list-by-department',
    domain: 'Organization',
    title: '部门岗位列表',
    method: 'GET',
    path: '/departments/{id}/positions',
    pathParams: [{ name: 'id', label: '部门 ID' }],
  },
  {
    id: 'position-get',
    domain: 'Organization',
    title: '岗位详情',
    method: 'GET',
    path: '/positions/{id}',
    pathParams: [{ name: 'id', label: '岗位 ID' }],
  },
  {
    id: 'position-update',
    domain: 'Organization',
    title: '更新岗位',
    method: 'PATCH',
    path: '/positions/{id}',
    pathParams: [{ name: 'id', label: '岗位 ID' }],
    bodyTemplate: {
      name: 'Workflow Owner',
      description: 'Updated position profile',
      permission_level: 'L3',
      required_capabilities: ['planning', 'approval', 'review'],
      status: 'active',
      sort_order: 20,
      metadata: {},
    },
  },
  {
    id: 'position-assignment-create',
    domain: 'Organization',
    title: '创建岗位适配',
    method: 'POST',
    path: '/positions/{id}/assignments',
    pathParams: [{ name: 'id', label: '岗位 ID' }],
    bodyTemplate: {
      actor_id: '',
      actor_type: 'internal_human',
      assignment_type: 'primary',
      allocation_percent: 100,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'position-assignment-list',
    domain: 'Organization',
    title: '岗位适配列表',
    method: 'GET',
    path: '/positions/{id}/assignments',
    pathParams: [{ name: 'id', label: '岗位 ID' }],
  },
  {
    id: 'position-assignment-update',
    domain: 'Organization',
    title: '更新岗位适配',
    method: 'PATCH',
    path: '/position-assignments/{id}',
    pathParams: [{ name: 'id', label: '岗位适配 ID' }],
    bodyTemplate: {
      assignment_type: 'backup',
      allocation_percent: 50,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'position-assignment-remove',
    domain: 'Organization',
    title: '移除岗位适配',
    method: 'DELETE',
    path: '/position-assignments/{id}',
    pathParams: [{ name: 'id', label: '岗位适配 ID' }],
  },
  {
    id: 'external-member-create',
    domain: 'Organization',
    title: '创建外部成员',
    method: 'POST',
    path: '/external-members',
    bodyTemplate: {
      name: 'External Consultant',
      email: 'consultant@example.com',
      vendor: 'Partner Co',
      contract_type: 'advisor',
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'external-member-list',
    domain: 'Organization',
    title: '外部成员列表',
    method: 'GET',
    path: '/external-members',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'external-member-get',
    domain: 'Organization',
    title: '外部成员详情',
    method: 'GET',
    path: '/external-members/{id}',
    pathParams: [{ name: 'id', label: '外部成员 ID' }],
  },
  {
    id: 'external-member-update',
    domain: 'Organization',
    title: '更新外部成员',
    method: 'PATCH',
    path: '/external-members/{id}',
    pathParams: [{ name: 'id', label: '外部成员 ID' }],
    bodyTemplate: {
      vendor: 'Partner Co',
      contract_type: 'delivery',
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'organization-members',
    domain: 'Organization',
    title: '组织成员列表',
    method: 'GET',
    path: '/organizations/{id}/members',
    pathParams: [{ name: 'id', label: '组织 ID' }],
    queryParams: [
      { name: 'department_id', label: '部门 ID' },
      { name: 'member_type', label: '成员类型', placeholder: 'internal | external | agent' },
    ],
  },
  {
    id: 'department-add-member',
    domain: 'Organization',
    title: '部门添加成员',
    method: 'POST',
    path: '/departments/{id}/members',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    bodyTemplate: {
      member_type: 'internal',
      user_id: '',
      external_member_id: null,
      agent_id: null,
      title: 'Engineering Lead',
      role_id: null,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'department-members',
    domain: 'Organization',
    title: '部门成员列表',
    method: 'GET',
    path: '/departments/{id}/members',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    queryParams: [{ name: 'member_type', label: '成员类型', placeholder: 'internal | external | agent' }],
  },
  {
    id: 'membership-update',
    domain: 'Organization',
    title: '更新成员关系',
    method: 'PATCH',
    path: '/memberships/{id}',
    pathParams: [{ name: 'id', label: '成员关系 ID' }],
    bodyTemplate: {
      title: 'Senior Engineer',
      role_id: null,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'membership-remove',
    domain: 'Organization',
    title: '移除组织成员',
    method: 'DELETE',
    path: '/memberships/{id}',
    pathParams: [{ name: 'id', label: '成员关系 ID' }],
  },
  {
    id: 'department-link-mvru',
    domain: 'Organization',
    title: '关联部门与 MVRU',
    method: 'POST',
    path: '/departments/{id}/mvru-links',
    pathParams: [{ name: 'id', label: '部门 ID' }],
    bodyTemplate: {
      mvru_id: '',
      link_type: 'execution',
      metadata: {},
    },
  },
  {
    id: 'department-mvru-links',
    domain: 'Organization',
    title: '部门 MVRU 关联',
    method: 'GET',
    path: '/departments/{id}/mvru-links',
    pathParams: [{ name: 'id', label: '部门 ID' }],
  },
  {
    id: 'organization-match-members',
    domain: 'Organization',
    title: '匹配成员',
    method: 'POST',
    path: '/organization/match-members',
    bodyTemplate: {
      organization_id: '',
      department_id: null,
      position_id: null,
      task_description: 'review launch readiness',
      workflow_template_id: null,
      required_capabilities: ['review'],
      required_level: 'L2',
      risk_level: 'medium',
      member_types: ['internal', 'agent'],
    },
  },
  {
    id: 'organization-match-capabilities',
    domain: 'Organization',
    title: '能力匹配桥接',
    method: 'POST',
    path: '/organization/match-capabilities',
    bodyTemplate: {
      department_id: null,
      task_description: 'review launch readiness',
      required_capabilities: ['review'],
      required_level: 'L2',
      risk_level: 'medium',
      context: {},
    },
  },
  {
    id: 'mvru-create',
    domain: 'Organization',
    title: '创建 MVRU',
    method: 'POST',
    path: '/muvrs',
    bodyTemplate: {
      organization_id: '',
      name: 'Decision Ops',
      description: 'Decision support unit',
      boundary: {
        data_permissions: [],
        resource_quota: {},
        network_policies: [],
      },
      config: {},
      parent_id: null,
    },
  },
  {
    id: 'mvru-get',
    domain: 'Organization',
    title: 'MVRU 详情',
    method: 'GET',
    path: '/muvrs/{id}',
    pathParams: [{ name: 'id', label: 'MVRU ID' }],
  },
  {
    id: 'mvru-status',
    domain: 'Organization',
    title: '更新 MVRU 状态',
    method: 'PATCH',
    path: '/muvrs/{id}/status',
    pathParams: [{ name: 'id', label: 'MVRU ID' }],
    bodyTemplate: {
      status: 'active',
    },
  },
  {
    id: 'mvru-add-member',
    domain: 'Organization',
    title: '添加成员',
    method: 'POST',
    path: '/muvrs/{id}/members',
    pathParams: [{ name: 'id', label: 'MVRU ID' }],
    bodyTemplate: {
      user_id: '',
      agent_id: null,
      role_id: '',
    },
  },
  {
    id: 'mvru-remove-member',
    domain: 'Organization',
    title: '移除成员',
    method: 'DELETE',
    path: '/muvrs/{id}/members',
    pathParams: [{ name: 'id', label: 'MVRU ID' }],
    bodyTemplate: {
      user_id: '',
      agent_id: null,
    },
  },
  {
    id: 'relationship-create',
    domain: 'Organization',
    title: '创建 MVRU 关系',
    method: 'POST',
    path: '/relationships',
    bodyTemplate: {
      source_mvru_id: '',
      target_mvru_id: '',
      rel_type: 'collaborate',
      config: {},
    },
  },
  {
    id: 'layer-classify',
    domain: 'Layer',
    title: '任务分层',
    method: 'POST',
    path: '/layers/classify',
    bodyTemplate: {
      task_description: 'Review a strategic compliance initiative',
      complexity_score: 0.5,
      risk_score: 0.3,
      strategic_score: 0.7,
      metadata: {},
    },
  },
  {
    id: 'layer-get-config',
    domain: 'Layer',
    title: '读取层配置',
    method: 'GET',
    path: '/layers/config/{mvruId}',
    pathParams: [{ name: 'mvruId', label: 'MVRU ID' }],
    queryParams: [{ name: 'layer', label: '层级', placeholder: 'strategic | tactical | operational' }],
  },
  {
    id: 'layer-set-config',
    domain: 'Layer',
    title: '保存层配置',
    method: 'PUT',
    path: '/layers/config/{mvruId}',
    pathParams: [{ name: 'mvruId', label: 'MVRU ID' }],
    bodyTemplate: {
      layer: 'tactical',
      config: {
        routing: 'balanced',
      },
    },
  },
  {
    id: 'layer-list-rules',
    domain: 'Layer',
    title: '路由规则',
    method: 'GET',
    path: '/layers/rules',
  },
  {
    id: 'capability-create',
    domain: 'Capability',
    title: '创建能力',
    method: 'POST',
    path: '/capabilities',
    bodyTemplate: {
      name: 'summarize-report',
      version: '1.0',
      description: 'Summarize operating reports',
      input_schema: {},
      output_schema: {},
      preconditions: [],
      error_handling: {},
      permission_level: 'L2',
      cost_estimate: {},
    },
  },
  {
    id: 'capability-list',
    domain: 'Capability',
    title: '能力列表',
    method: 'GET',
    path: '/capabilities',
  },
  {
    id: 'capability-get',
    domain: 'Capability',
    title: '能力详情',
    method: 'GET',
    path: '/capabilities/{id}',
    pathParams: [{ name: 'id', label: '能力 ID' }],
  },
  {
    id: 'capability-match',
    domain: 'Capability',
    title: '能力匹配',
    method: 'POST',
    path: '/capabilities/match',
    bodyTemplate: {
      task_description: 'summarize weekly operating metrics',
      required_level: 'L2',
      metadata: {},
    },
  },
  {
    id: 'capability-create-evaluation',
    domain: 'Capability',
    title: '创建能力评估',
    method: 'POST',
    path: '/capabilities/evaluations',
    bodyTemplate: {
      capability_id: null,
      actor_id: null,
      actor_type: 'internal_agent',
      workflow_id: null,
      task_id: null,
      evaluator_id: null,
      evaluator_type: 'human',
      quality_score: 0.8,
      reliability_score: 0.75,
      cost_score: 0.7,
      latency_score: 0.7,
      risk_score: 0.65,
      compliance_score: 0.8,
      evidence: { risk_level: 'medium' },
      conclusion: 'human-reviewed capability evaluation',
    },
  },
  {
    id: 'capability-list-evaluations',
    domain: 'Capability',
    title: '能力评估列表',
    method: 'GET',
    path: '/capabilities/evaluations',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'capability-list-one-evaluations',
    domain: 'Capability',
    title: '单能力评估列表',
    method: 'GET',
    path: '/capabilities/{id}/evaluations',
    pathParams: [{ name: 'id', label: '能力 ID' }],
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'capability-bind',
    domain: 'Capability',
    title: '绑定能力',
    method: 'POST',
    path: '/bindings',
    bodyTemplate: {
      capability_id: '',
      mvru_id: '',
      config: {},
    },
  },
  {
    id: 'capability-unbind',
    domain: 'Capability',
    title: '解绑能力',
    method: 'DELETE',
    path: '/bindings/{id}',
    pathParams: [{ name: 'id', label: '绑定 ID' }],
  },
  {
    id: 'capability-list-bindings',
    domain: 'Capability',
    title: 'MVRU 绑定能力',
    method: 'GET',
    path: '/bindings',
    queryParams: [{ name: 'mvru_id', label: 'MVRU ID' }],
  },
  {
    id: 'workflow-create-template',
    domain: 'Workflow',
    title: '创建工作流模板',
    method: 'POST',
    path: '/workflows/templates',
    bodyTemplate: {
      name: 'PER Review',
      description: 'Planner Executor Reviewer workflow',
      organization_id: null,
      department_id: null,
      stages: [
        {
          id: 'plan-1',
          type: 'plan',
          name: 'Planning',
          assignee_type: 'internal',
          position_id: null,
          position_code: null,
          required_capabilities: ['planning'],
          required_permission_level: 'L1',
          required_roles: ['planner'],
          risk_level: 'low',
          preferred_actor_types: ['internal_human'],
          evaluation_policy: { primary_reviewer: 'human' },
          matching_policy: { ranking: 'capability_weight_access' },
        },
        {
          id: 'execute-1',
          type: 'execute',
          name: 'Execution',
          assignee_type: 'either',
          position_id: null,
          position_code: null,
          required_capabilities: ['execution'],
          required_permission_level: 'L2',
          required_roles: ['executor'],
          risk_level: 'medium',
          preferred_actor_types: ['internal_human', 'internal_agent'],
          evaluation_policy: { primary_reviewer: 'human' },
          matching_policy: { ranking: 'capability_weight_access' },
        },
        {
          id: 'review-1',
          type: 'review',
          name: 'Review',
          assignee_type: 'internal',
          position_id: null,
          position_code: null,
          required_capabilities: ['review'],
          required_permission_level: 'L2',
          required_roles: ['reviewer'],
          risk_level: 'medium',
          preferred_actor_types: ['internal_human'],
          evaluation_policy: { primary_reviewer: 'human', update_weight: true },
          matching_policy: { ranking: 'capability_weight_access' },
        },
      ],
      assignee_type: 'either',
      required_weight: 0.5,
      routing_rules: {},
      visual_graph: {
        nodes: [],
        edges: [],
      },
    },
  },
  {
    id: 'workflow-list-templates',
    domain: 'Workflow',
    title: '模板列表',
    method: 'GET',
    path: '/workflows/templates',
  },
  {
    id: 'workflow-get-template',
    domain: 'Workflow',
    title: '模板详情',
    method: 'GET',
    path: '/workflows/templates/{id}',
    pathParams: [{ name: 'id', label: '模板 ID' }],
  },
  {
    id: 'workflow-start',
    domain: 'Workflow',
    title: '启动工作流',
    method: 'POST',
    path: '/workflows/instances',
    bodyTemplate: {
      template_id: '',
      organization_id: null,
      department_id: null,
      project_id: null,
      context: {
        objective: 'Review launch readiness',
      },
    },
  },
  {
    id: 'workflow-get',
    domain: 'Workflow',
    title: '工作流详情',
    method: 'GET',
    path: '/workflows/instances/{id}',
    pathParams: [{ name: 'id', label: '工作流 ID' }],
  },
  {
    id: 'workflow-status',
    domain: 'Workflow',
    title: '更新工作流状态',
    method: 'PATCH',
    path: '/workflows/instances/{id}/status',
    pathParams: [{ name: 'id', label: '工作流 ID' }],
    bodyTemplate: {
      status: 'paused',
    },
  },
  {
    id: 'workflow-complete-task',
    domain: 'Workflow',
    title: '完成任务',
    method: 'PATCH',
    path: '/tasks/{id}/status',
    pathParams: [{ name: 'id', label: '任务 ID' }],
    bodyTemplate: {
      output: {
        summary: 'done',
      },
    },
  },
  {
    id: 'workflow-decision',
    domain: 'Workflow',
    title: '记录决策',
    method: 'POST',
    path: '/tasks/{id}/decisions',
    pathParams: [{ name: 'id', label: '任务 ID' }],
    bodyTemplate: {
      decision_maker_id: '',
      maker_type: 'human',
      reasoning: 'Weighted decision record',
      outcome: 'approved',
      input: {},
      output: {},
    },
  },
  {
    id: 'workflow-get-context',
    domain: 'Workflow',
    title: '读取上下文',
    method: 'GET',
    path: '/workflows/instances/{id}/context',
    pathParams: [{ name: 'id', label: '工作流 ID' }],
  },
  {
    id: 'workflow-update-context',
    domain: 'Workflow',
    title: '更新上下文',
    method: 'PUT',
    path: '/workflows/instances/{id}/context',
    pathParams: [{ name: 'id', label: '工作流 ID' }],
    bodyTemplate: {
      working_memory: {},
      injected_experience: [],
      principle_notes: '',
    },
  },
  {
    id: 'observability-start-trace',
    domain: 'Observability',
    title: '开始 Trace',
    method: 'POST',
    path: '/traces',
    bodyTemplate: {
      workflow_id: null,
      metadata: {},
    },
  },
  {
    id: 'observability-list-traces',
    domain: 'Observability',
    title: 'Trace 列表',
    method: 'GET',
    path: '/traces',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'observability-get-trace',
    domain: 'Observability',
    title: 'Trace 详情',
    method: 'GET',
    path: '/traces/{id}',
    pathParams: [{ name: 'id', label: 'Trace ID' }],
  },
  {
    id: 'observability-record-span',
    domain: 'Observability',
    title: '记录 Span',
    method: 'POST',
    path: '/traces/{id}/spans',
    pathParams: [{ name: 'id', label: 'Trace ID' }],
    bodyTemplate: {
      span_type: 'task',
      entity_id: null,
      entity_type: 'task',
      actor_id: null,
      actor_type: 'human',
      input: {},
      output: {},
      duration_ms: 120,
      metadata: {},
    },
  },
  {
    id: 'observability-complete-trace',
    domain: 'Observability',
    title: '完成 Trace',
    method: 'POST',
    path: '/traces/{id}/complete',
    pathParams: [{ name: 'id', label: 'Trace ID' }],
    bodyTemplate: {
      status: 'completed',
    },
  },
  {
    id: 'observability-record-metric',
    domain: 'Observability',
    title: '记录指标',
    method: 'POST',
    path: '/metrics',
    bodyTemplate: {
      metric_type: 'health',
      metric_name: 'workflow_quality',
      entity_id: null,
      entity_type: 'workflow',
      value: 0.92,
      metadata: {},
    },
  },
  {
    id: 'observability-query-metrics',
    domain: 'Observability',
    title: '查询指标',
    method: 'GET',
    path: '/metrics',
    queryParams: [
      { name: 'metric_type', label: '类型' },
      { name: 'metric_name', label: '名称' },
      { name: 'limit', label: '数量', placeholder: '50' },
    ],
  },
  {
    id: 'verification-create-report',
    domain: 'Verification',
    title: '创建验证报告',
    method: 'POST',
    path: '/verification/reports',
    bodyTemplate: {
      workflow_id: null,
      task_id: null,
      result_score: 0.9,
      path_score: 0.8,
      environment_score: 0.85,
      conclusion: 'passed',
      suggestions: [],
    },
  },
  {
    id: 'verification-list-reports',
    domain: 'Verification',
    title: '报告列表',
    method: 'GET',
    path: '/verification/reports',
    queryParams: [
      { name: 'workflow_id', label: '工作流 ID' },
      { name: 'limit', label: '数量', placeholder: '50' },
    ],
  },
  {
    id: 'verification-get-report',
    domain: 'Verification',
    title: '报告详情',
    method: 'GET',
    path: '/verification/reports/{id}',
    pathParams: [{ name: 'id', label: '报告 ID' }],
  },
  {
    id: 'verification-assign-review',
    domain: 'Verification',
    title: '分配复核',
    method: 'POST',
    path: '/verification/reports/{id}/reviews',
    pathParams: [{ name: 'id', label: '报告 ID' }],
    bodyTemplate: {
      level: 'L1',
      reviewer_id: null,
      reviewer_type: 'machine',
    },
  },
  {
    id: 'verification-complete-review',
    domain: 'Verification',
    title: '完成复核',
    method: 'PATCH',
    path: '/verification/reviews/{id}',
    pathParams: [{ name: 'id', label: '复核 ID' }],
    bodyTemplate: {
      result: {
        status: 'approved',
      },
    },
  },
  {
    id: 'governance-create-permission',
    domain: 'Governance',
    title: '创建权限',
    method: 'POST',
    path: '/governance/permissions',
    bodyTemplate: {
      level: 2,
      name: 'workflow.execute',
      description: 'Execute workflow task',
      behavior: 'notify',
    },
  },
  {
    id: 'governance-list-permissions',
    domain: 'Governance',
    title: '权限列表',
    method: 'GET',
    path: '/governance/permissions',
  },
  {
    id: 'governance-create-principle',
    domain: 'Governance',
    title: '创建原则',
    method: 'POST',
    path: '/governance/principles',
    bodyTemplate: {
      name: 'least privilege',
      description: 'Prefer minimum required authority',
      evaluation_logic: {},
      priority: 10,
    },
  },
  {
    id: 'governance-list-principles',
    domain: 'Governance',
    title: '原则列表',
    method: 'GET',
    path: '/governance/principles',
  },
  {
    id: 'governance-get-principle',
    domain: 'Governance',
    title: '原则详情',
    method: 'GET',
    path: '/governance/principles/{id}',
    pathParams: [{ name: 'id', label: '原则 ID' }],
  },
  {
    id: 'governance-create-rule',
    domain: 'Governance',
    title: '创建控制规则',
    method: 'POST',
    path: '/governance/control-rules',
    bodyTemplate: {
      principle_id: null,
      target_entity_type: 'workflow',
      target_entity_id: null,
      condition: {},
      action: 'notify',
      priority: 1,
    },
  },
  {
    id: 'governance-list-rules',
    domain: 'Governance',
    title: '控制规则列表',
    method: 'GET',
    path: '/governance/control-rules',
  },
  {
    id: 'governance-check',
    domain: 'Governance',
    title: '权限检查',
    method: 'POST',
    path: '/governance/check',
    bodyTemplate: {
      user_id: '',
      action: 'execute',
      resource: 'workflow',
      resource_id: null,
    },
  },
  {
    id: 'governance-access-decide',
    domain: 'Governance',
    title: '准入决策',
    method: 'POST',
    path: '/governance/access/decide',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'internal_human',
      action: 'workflow.assign',
      resource: 'workflow_task',
      resource_id: null,
      organization_id: null,
      department_id: null,
      workflow_id: null,
      task_id: null,
      capability_id: null,
      required_level: 'L2',
      risk_level: 'medium',
      weight_snapshot: 0.65,
      context: {},
    },
  },
  {
    id: 'governance-access-decisions',
    domain: 'Governance',
    title: '准入审计列表',
    method: 'GET',
    path: '/governance/access/decisions',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'governance-get-user-preference',
    domain: 'Governance',
    title: 'operation.preference.get',
    method: 'GET',
    path: '/preferences/{key}',
    pathParams: [{ name: 'key', label: 'operation.preference.key', placeholder: 'workspace.layout.widths.v1' }],
    operationKind: 'direct',
    dangerLevel: 'low',
    resultView: 'detail',
  },
  {
    id: 'governance-save-user-preference',
    domain: 'Governance',
    title: 'operation.preference.save',
    method: 'PUT',
    path: '/preferences/{key}',
    pathParams: [{ name: 'key', label: 'operation.preference.key', placeholder: 'workspace.layout.widths.v1' }],
    bodyTemplate: {
      value: {
        menu: 248,
        business: 300,
        status: 340,
      },
    },
    operationKind: 'direct',
    dangerLevel: 'low',
    resultView: 'detail',
  },
  {
    id: 'evolution-compute-weight',
    domain: 'Evolution',
    title: '计算权重',
    method: 'POST',
    path: '/evolution/weights/compute',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'human',
      task_context: {},
      required_level: 'L2',
    },
  },
  {
    id: 'evolution-record-outcome',
    domain: 'Evolution',
    title: '记录结果',
    method: 'POST',
    path: '/evolution/weights/outcome',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'human',
      outcome_score: 0.8,
      task_context: {},
    },
  },
  {
    id: 'evolution-get-weight',
    domain: 'Evolution',
    title: '权重详情',
    method: 'GET',
    path: '/evolution/weights/{actorType}/{actorID}',
    pathParams: [
      { name: 'actorType', label: '参与者类型', placeholder: 'human | ai' },
      { name: 'actorID', label: '参与者 ID' },
    ],
  },
  {
    id: 'evolution-compute-context-weight',
    domain: 'Evolution',
    title: '计算上下文权重',
    method: 'POST',
    path: '/evolution/context-weights/compute',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'internal_human',
      required_level: 'L2',
      scope: {
        organization_id: null,
        department_id: null,
        workflow_template_id: null,
        workflow_stage: 'review',
        task_type: 'review launch readiness',
        capability_id: null,
        risk_level: 'medium',
        context: {},
      },
    },
  },
  {
    id: 'evolution-record-context-outcome',
    domain: 'Evolution',
    title: '记录上下文结果',
    method: 'POST',
    path: '/evolution/context-weights/outcome',
    bodyTemplate: {
      actor_id: '',
      actor_type: 'internal_human',
      outcome_score: 0.85,
      scope: {
        organization_id: null,
        department_id: null,
        workflow_template_id: null,
        workflow_stage: 'review',
        task_type: 'review launch readiness',
        capability_id: null,
        risk_level: 'medium',
        context: {},
      },
    },
  },
  {
    id: 'evolution-list-context-weights',
    domain: 'Evolution',
    title: '上下文权重列表',
    method: 'GET',
    path: '/evolution/context-weights',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'evolution-list-weights',
    domain: 'Evolution',
    title: '权重列表',
    method: 'GET',
    path: '/evolution/weights',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'evolution-get-alpha',
    domain: 'Evolution',
    title: 'Alpha 配置',
    method: 'GET',
    path: '/evolution/alphas',
  },
  {
    id: 'evolution-update-alpha',
    domain: 'Evolution',
    title: '更新 Alpha',
    method: 'PUT',
    path: '/evolution/alphas',
    bodyTemplate: {
      alpha_expertise: 0.25,
      alpha_track_record: 0.2,
      alpha_reliability: 0.15,
      alpha_recency: 0.1,
      alpha_context_fit: 0.1,
      alpha_principle: 0.2,
    },
  },
  {
    id: 'evolution-create-experiment',
    domain: 'Evolution',
    title: '创建实验',
    method: 'POST',
    path: '/evolution/experiments',
    bodyTemplate: {
      name: 'Routing alpha test',
      hypothesis: 'Higher reliability weight improves review quality',
      mvru_id: null,
      alpha_overrides: {},
      success_criteria: {},
    },
  },
  {
    id: 'evolution-list-experiments',
    domain: 'Evolution',
    title: '实验列表',
    method: 'GET',
    path: '/evolution/experiments',
  },
  {
    id: 'evolution-update-experiment',
    domain: 'Evolution',
    title: '更新实验状态',
    method: 'PATCH',
    path: '/evolution/experiments/{id}',
    pathParams: [{ name: 'id', label: '实验 ID' }],
    bodyTemplate: {
      status: 'running',
      conclusion: '',
    },
  },
  {
    id: 'evolution-create-knowledge',
    domain: 'Evolution',
    title: '创建知识',
    method: 'POST',
    path: '/evolution/knowledge',
    bodyTemplate: {
      workflow_id: null,
      title: 'Review heuristic',
      content: 'High risk changes should receive L2 review.',
      tags: ['review', 'risk'],
      source: 'manual',
    },
  },
  {
    id: 'evolution-list-knowledge',
    domain: 'Evolution',
    title: '知识列表',
    method: 'GET',
    path: '/evolution/knowledge',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'evolution-create-signal',
    domain: 'Evolution',
    title: '创建信号',
    method: 'POST',
    path: '/evolution/signals',
    bodyTemplate: {
      signal_type: 'metric_shift',
      source: 'manual',
      priority: 5,
      data: {},
    },
  },
  {
    id: 'evolution-list-signals',
    domain: 'Evolution',
    title: '信号列表',
    method: 'GET',
    path: '/evolution/signals',
    queryParams: [
      { name: 'acknowledged', label: '已确认', placeholder: 'true | false' },
      { name: 'limit', label: '数量', placeholder: '50' },
    ],
  },
  {
    id: 'evolution-ack-signal',
    domain: 'Evolution',
    title: '确认信号',
    method: 'POST',
    path: '/evolution/signals/{id}/acknowledge',
    pathParams: [{ name: 'id', label: '信号 ID' }],
  },
  {
    id: 'requirement-create',
    domain: 'Requirement',
    title: '创建需求',
    method: 'POST',
    path: '/requirements',
    bodyTemplate: {
      title: '业务流程自动化需求',
      description: '从需求拆解到项目交付与反馈评估',
      source: 'manual',
      priority: 'medium',
      risk_level: 'medium',
      required_level: 'L2',
      organization_id: null,
      department_id: null,
      metadata: {},
    },
  },
  {
    id: 'requirement-list',
    domain: 'Requirement',
    title: '需求列表',
    method: 'GET',
    path: '/requirements',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'requirement-get',
    domain: 'Requirement',
    title: '需求详情',
    method: 'GET',
    path: '/requirements/{id}',
    pathParams: [{ name: 'id', label: '需求 ID' }],
  },
  {
    id: 'requirement-update',
    domain: 'Requirement',
    title: '更新需求',
    method: 'PATCH',
    path: '/requirements/{id}',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {
      status: 'analyzed',
      priority: 'high',
      risk_level: 'medium',
      required_level: 'L2',
      metadata: {},
    },
  },
  {
    id: 'requirement-analyze',
    domain: 'Requirement',
    title: '分析需求',
    method: 'POST',
    path: '/requirements/{id}/analyze',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {
      notes: 'agent assisted requirement analysis',
    },
  },
  {
    id: 'requirement-approve',
    domain: 'Requirement',
    title: '审批需求',
    method: 'POST',
    path: '/requirements/{id}/approve',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {},
  },
  {
    id: 'requirement-documents',
    domain: 'Requirement',
    title: '需求文档列表',
    method: 'GET',
    path: '/requirements/{id}/documents',
    pathParams: [{ name: 'id', label: '需求 ID' }],
  },
  {
    id: 'requirement-start-analysis-workflow',
    domain: 'Requirement',
    title: '启动分析流程',
    method: 'POST',
    path: '/requirements/{id}/analysis-workflows',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {
      workflow_template_id: '',
      purpose: 'requirement_analysis',
      context: {},
      metadata: {},
    },
  },
  {
    id: 'requirement-list-analysis-workflows',
    domain: 'Requirement',
    title: '分析流程列表',
    method: 'GET',
    path: '/requirements/{id}/analysis-workflows',
    pathParams: [{ name: 'id', label: '需求 ID' }],
  },
  {
    id: 'requirement-sync-analysis-workflow',
    domain: 'Requirement',
    title: '同步分析结果',
    method: 'POST',
    path: '/requirements/{id}/analysis-workflows/{workflowID}/sync',
    pathParams: [
      { name: 'id', label: '需求 ID' },
      { name: 'workflowID', label: '工作流 ID' },
    ],
    bodyTemplate: {},
  },
  {
    id: 'requirement-convert',
    domain: 'Requirement',
    title: '需求转项目',
    method: 'POST',
    path: '/requirements/{id}/convert-to-project',
    pathParams: [{ name: 'id', label: '需求 ID' }],
    bodyTemplate: {
      budget_amount: 5000,
      metadata: {},
    },
  },
  {
    id: 'project-create',
    domain: 'Project',
    title: '创建项目',
    method: 'POST',
    path: '/projects',
    operationKind: 'direct',
    dangerLevel: 'low',
    requiresEntityContext: false,
    bodyTemplate: {
      requirement_id: null,
      organization_id: null,
      department_id: null,
      name: '需求驱动交付项目',
      description: '项目过程管控、交付、成本核算和反馈评估',
      status: 'planning',
      priority: 'medium',
      risk_level: 'medium',
      required_level: 'L2',
      budget_amount: 5000,
      metadata: {},
    },
  },
  {
    id: 'project-list',
    domain: 'Project',
    title: '项目列表',
    method: 'GET',
    path: '/projects',
    queryParams: [{ name: 'limit', label: '数量', placeholder: '50' }],
  },
  {
    id: 'project-get',
    domain: 'Project',
    title: '项目详情',
    method: 'GET',
    path: '/projects/{id}',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'project-overview',
    domain: 'Project',
    title: '项目总览',
    method: 'GET',
    path: '/projects/{id}/overview',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'project-update',
    domain: 'Project',
    title: '更新项目',
    method: 'PATCH',
    path: '/projects/{id}',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      name: 'Updated project',
      status: 'active',
      budget_amount: 8000,
      metadata: {},
    },
  },
  {
    id: 'project-status',
    domain: 'Project',
    title: '更新项目状态',
    method: 'POST',
    path: '/projects/{id}/status',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      status: 'delivering',
      note: 'process checkpoint',
    },
  },
  {
    id: 'project-add-member',
    domain: 'Project',
    title: '添加项目成员',
    method: 'POST',
    path: '/projects/{id}/members',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      member_actor_id: '',
      member_actor_type: 'internal_human',
      position_id: null,
      position_assignment_id: null,
      role: 'owner',
      title: 'Project Owner',
      allocation_percent: 100,
      cost_rate: 800,
      permission_level: 'L2',
      capabilities: ['planning', 'delivery', 'review'],
      metadata: {},
    },
  },
  {
    id: 'project-list-members',
    domain: 'Project',
    title: '项目成员',
    method: 'GET',
    path: '/projects/{id}/members',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'project-bind-workflow',
    domain: 'Project',
    title: '绑定项目流程',
    method: 'POST',
    path: '/projects/{id}/workflows',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      workflow_id: null,
      workflow_template_id: null,
      purpose: 'delivery',
      metadata: {},
    },
  },
  {
    id: 'project-match-actors',
    domain: 'Project',
    title: '匹配项目成员',
    method: 'POST',
    path: '/projects/{id}/match-actors',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      task_description: '需求拆解、执行交付与人工验收',
      required_capabilities: ['planning', 'delivery', 'review'],
      required_level: 'L2',
      risk_level: 'medium',
      member_types: ['internal', 'external', 'agent'],
    },
  },
  {
    id: 'delivery-create',
    domain: 'Delivery',
    title: '创建交付物',
    method: 'POST',
    path: '/projects/{id}/deliverables',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      name: '交付物 v1',
      deliverable_type: 'document',
      uri: '',
      version: '1.0',
      status: 'draft',
      metadata: {},
    },
  },
  {
    id: 'delivery-list',
    domain: 'Delivery',
    title: '交付物列表',
    method: 'GET',
    path: '/projects/{id}/deliverables',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'delivery-update',
    domain: 'Delivery',
    title: '更新交付物',
    method: 'PATCH',
    path: '/deliverables/{id}',
    pathParams: [{ name: 'id', label: '交付物 ID' }],
    bodyTemplate: {
      name: 'Updated deliverable',
      status: 'draft',
      metadata: {},
    },
  },
  {
    id: 'delivery-submit',
    domain: 'Delivery',
    title: '提交交付物',
    method: 'POST',
    path: '/deliverables/{id}/submit',
    pathParams: [{ name: 'id', label: '交付物 ID' }],
    bodyTemplate: { evidence: {} },
  },
  {
    id: 'delivery-accept',
    domain: 'Delivery',
    title: '验收交付物',
    method: 'POST',
    path: '/deliverables/{id}/accept',
    pathParams: [{ name: 'id', label: '交付物 ID' }],
    bodyTemplate: { evidence: {} },
  },
  {
    id: 'delivery-reject',
    domain: 'Delivery',
    title: '退回交付物',
    method: 'POST',
    path: '/deliverables/{id}/reject',
    pathParams: [{ name: 'id', label: '交付物 ID' }],
    bodyTemplate: {
      reason: 'needs revision',
      evidence: {},
    },
  },
  {
    id: 'cost-create',
    domain: 'Cost',
    title: '写入成本',
    method: 'POST',
    path: '/projects/{id}/cost-entries',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      source_type: 'manual',
      entry_actor_id: null,
      entry_actor_type: 'internal_human',
      amount: 1000,
      currency: 'CNY',
      description: 'manual cost entry',
      metadata: {},
    },
  },
  {
    id: 'cost-list',
    domain: 'Cost',
    title: '成本明细',
    method: 'GET',
    path: '/projects/{id}/cost-entries',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'cost-summary',
    domain: 'Cost',
    title: '成本汇总',
    method: 'GET',
    path: '/projects/{id}/cost-summary',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'cost-refresh',
    domain: 'Cost',
    title: '刷新成员成本',
    method: 'POST',
    path: '/projects/{id}/cost-refresh',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {},
  },
  {
    id: 'feedback-create',
    domain: 'Feedback',
    title: '创建项目评估',
    method: 'POST',
    path: '/projects/{id}/evaluations',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      evaluated_actor_id: null,
      evaluated_actor_type: 'internal_human',
      capability_id: null,
      quality_score: 0.8,
      delivery_score: 0.8,
      cost_score: 0.75,
      collaboration_score: 0.8,
      conclusion: 'human-reviewed project delivery',
      evidence: {},
    },
  },
  {
    id: 'feedback-list',
    domain: 'Feedback',
    title: '项目评估列表',
    method: 'GET',
    path: '/projects/{id}/evaluations',
    pathParams: [{ name: 'id', label: '项目 ID' }],
  },
  {
    id: 'feedback-close',
    domain: 'Feedback',
    title: '闭环反馈',
    method: 'POST',
    path: '/projects/{id}/close-feedback',
    pathParams: [{ name: 'id', label: '项目 ID' }],
    bodyTemplate: {
      outcome_score: 0.8,
      conclusion: 'project closed with feedback',
      metadata: {},
    },
  },
  {
    id: 'meta-org-overview',
    domain: 'MetaOrg',
    title: 'Meta-Org 总览',
    method: 'GET',
    path: '/meta-org/overview',
  },
  {
    id: 'meta-org-inbox',
    domain: 'MetaOrg',
    title: 'Meta-Org 收件箱',
    method: 'GET',
    path: '/meta-org/inbox',
  },
  {
    id: 'meta-resource-list',
    domain: 'MetaResource',
    title: 'Meta 资源列表',
    method: 'GET',
    path: '/meta-resources',
    queryParams: [
      { name: 'resource_type', label: '资源类型' },
      { name: 'status', label: '状态' },
    ],
  },
  {
    id: 'meta-resource-create',
    domain: 'MetaResource',
    title: '创建 Meta 资源',
    method: 'POST',
    path: '/meta-resources',
    bodyTemplate: {
      resource_type: 'resource',
      name: 'sample resource',
      capability_profile: {},
      cost_profile: {},
      capacity_profile: {},
      risk_profile: {},
      performance_profile: {},
      metadata: {},
    },
  },
  {
    id: 'meta-resource-sync-existing',
    domain: 'MetaResource',
    title: '同步现有资源',
    method: 'POST',
    path: '/meta-resources/sync-existing',
  },
  {
    id: 'meta-resource-summary',
    domain: 'MetaResource',
    title: 'Meta 资源汇总',
    method: 'GET',
    path: '/meta-resources/summary',
  },
  {
    id: 'demand-profile-create',
    domain: 'MetaResource',
    title: '创建需求画像',
    method: 'POST',
    path: '/demand-profiles',
    bodyTemplate: {
      title: '需求驱动资源适配',
      goal: '从需求拆解能力并推荐资源组合',
      acceptance_criteria: [{ name: '满足业务目标', metric: 'accepted' }],
      required_capabilities: [{ name: 'planning', level: 'L2' }],
      budget_constraints: { currency: 'CNY', amount: 5000 },
      time_constraints: { deadline: '' },
      risk_constraints: { risk_level: 'medium' },
      resource_fit_candidates: [],
      metadata: {},
    },
  },
  {
    id: 'demand-profile-list',
    domain: 'MetaResource',
    title: '需求画像列表',
    method: 'GET',
    path: '/demand-profiles',
  },
  {
    id: 'pdca-cycle-create',
    domain: 'MetaResource',
    title: '创建 PDCA 循环',
    method: 'POST',
    path: '/pdca-cycles',
    bodyTemplate: {
      demand_profile_id: '',
      current_stage: 'plan',
      summary: 'plan demand-resource fit',
      metadata: {},
    },
  },
  {
    id: 'pdca-cycle-list',
    domain: 'MetaResource',
    title: 'PDCA 循环列表',
    method: 'GET',
    path: '/pdca-cycles',
  },
  {
    id: 'pdca-event-create',
    domain: 'MetaResource',
    title: '创建 PDCA 事件',
    method: 'POST',
    path: '/pdca-events',
    bodyTemplate: {
      cycle_id: '',
      stage: 'plan',
      event_type: 'resource_fit',
      resource_refs: [],
      cost_refs: [],
      evidence: {},
      decision: 'resource fit accepted for planning',
      next_action: 'start do stage',
      metadata: {},
    },
  },
  {
    id: 'pdca-event-list',
    domain: 'MetaResource',
    title: 'PDCA 事件列表',
    method: 'GET',
    path: '/pdca-events',
    queryParams: [{ name: 'cycle_id', label: 'PDCA 循环 ID' }],
  },
  {
    id: 'model-provider-create',
    domain: 'DeveloperTools',
    title: '创建模型供应商',
    method: 'POST',
    path: '/model-providers',
    bodyTemplate: {
      name: 'OpenAI Production',
      provider_type: 'openai',
      base_url: '',
      api_key: '',
      risk_level: 'medium',
      timeout_ms: 60000,
      retry_count: 1,
      tags: ['production'],
      metadata: {},
    },
  },
  {
    id: 'model-provider-list',
    domain: 'DeveloperTools',
    title: '模型供应商列表',
    method: 'GET',
    path: '/model-providers',
  },
  {
    id: 'model-provider-test',
    domain: 'DeveloperTools',
    title: '测试模型供应商',
    method: 'POST',
    path: '/model-providers/{id}/test',
    pathParams: [{ name: 'id', label: '模型供应商 ID' }],
    bodyTemplate: {
      model: 'gpt-4o-mini',
    },
  },
  {
    id: 'model-provider-channel-create',
    domain: 'DeveloperTools',
    title: '创建模型供应商通道',
    method: 'POST',
    path: '/model-providers/{id}/channels',
    pathParams: [{ name: 'id', label: '模型供应商 ID' }],
    bodyTemplate: {
      name: 'primary-channel',
      base_url: '',
      api_key: '',
      priority: 50,
      concurrency_limit: 0,
      load_factor: 1,
      rate_multiplier: 1,
      quota_amount: 0,
      quota_currency: 'CNY',
      supported_model_patterns: ['*'],
      model_mapping: {},
      metadata: {},
    },
  },
  {
    id: 'model-provider-channel-list',
    domain: 'DeveloperTools',
    title: '模型供应商通道列表',
    method: 'GET',
    path: '/model-provider-channels',
    queryParams: [{ name: 'provider_id', label: '模型供应商 ID' }],
  },
  {
    id: 'model-provider-channel-rotate-key',
    domain: 'DeveloperTools',
    title: '轮换模型通道密钥',
    method: 'POST',
    path: '/model-provider-channels/{id}/rotate-key',
    pathParams: [{ name: 'id', label: '通道 ID' }],
    bodyTemplate: {
      api_key: '',
    },
  },
  {
    id: 'model-provider-channel-test',
    domain: 'DeveloperTools',
    title: '测试模型通道',
    method: 'POST',
    path: '/model-provider-channels/{id}/test',
    pathParams: [{ name: 'id', label: '通道 ID' }],
    bodyTemplate: {
      model: 'gpt-4o-mini',
    },
  },
  {
    id: 'model-create',
    domain: 'DeveloperTools',
    title: '创建模型',
    method: 'POST',
    path: '/models',
    bodyTemplate: {
      provider_id: '',
      model_key: 'gpt-4o-mini',
      display_name: 'GPT-4o Mini',
      context_window: 128000,
      max_output_tokens: 4096,
      capabilities: ['chat', 'streaming', 'tool_calling'],
      input_price_per_1k: 0,
      output_price_per_1k: 0,
      cache_creation_price_per_1k: 0,
      cache_read_price_per_1k: 0,
      image_output_price_per_1k: 0,
      priority_input_price_per_1k: 0,
      priority_output_price_per_1k: 0,
      long_context_threshold: 0,
      long_context_input_multiplier: 1,
      long_context_output_multiplier: 1,
      currency: 'CNY',
      metadata: {},
    },
  },
  {
    id: 'model-list',
    domain: 'DeveloperTools',
    title: '模型目录',
    method: 'GET',
    path: '/models',
  },
  {
    id: 'ai-gateway-invocations',
    domain: 'DeveloperTools',
    title: '模型调用日志',
    method: 'GET',
    path: '/ai-gateway/invocations',
  },
  {
    id: 'ai-gateway-cost-summary',
    domain: 'DeveloperTools',
    title: '模型成本汇总',
    method: 'GET',
    path: '/ai-gateway/cost-summary',
  },
  {
    id: 'ai-gateway-routing-rule-create',
    domain: 'DeveloperTools',
    title: '创建 AI 路由规则',
    method: 'POST',
    path: '/ai-gateway/routing-rules',
    bodyTemplate: {
      name: 'default-route',
      provider_id: '',
      channel_id: '',
      match_scope: 'global',
      match_value: '',
      model_pattern: '*',
      priority: 100,
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'ai-gateway-routing-rule-list',
    domain: 'DeveloperTools',
    title: 'AI 路由规则列表',
    method: 'GET',
    path: '/ai-gateway/routing-rules',
  },
  {
    id: 'ai-gateway-usage-analysis',
    domain: 'DeveloperTools',
    title: 'AI 用量分析',
    method: 'GET',
    path: '/ai-gateway/usage-analysis',
  },
  {
    id: 'ai-gateway-estimate-cost',
    domain: 'DeveloperTools',
    title: '估算 AI 成本',
    method: 'POST',
    path: '/ai-gateway/estimate-cost',
    bodyTemplate: {
      provider_type: 'openai',
      model: 'gpt-4o-mini',
      service_tier: '',
      rate_multiplier: 1,
      usage: {
        input_tokens: 1000,
        output_tokens: 500,
        cache_creation_tokens: 0,
        cache_read_tokens: 0,
        image_output_tokens: 0,
      },
    },
  },
  {
    id: 'tool-list',
    domain: 'DeveloperTools',
    title: '工具注册表',
    method: 'GET',
    path: '/tools',
  },
  {
    id: 'tool-execution-list',
    domain: 'DeveloperTools',
    title: '工具执行日志',
    method: 'GET',
    path: '/tool-executions',
  },
  {
    id: 'finance-adapter-create',
    domain: 'FinanceAccounting',
    title: '创建财务适配器',
    method: 'POST',
    path: '/finance/adapters',
    operationKind: 'direct',
    dangerLevel: 'low',
    bodyTemplate: {
      name: 'Generic Finance Adapter',
      endpoint_url: 'https://finance.example.com/webhook',
      auth_type: 'hmac',
      secret: '',
      timeout_ms: 30000,
      retry_count: 3,
      metadata: {},
    },
  },
  {
    id: 'finance-adapter-list',
    domain: 'FinanceAccounting',
    title: '财务适配器列表',
    method: 'GET',
    path: '/finance/adapters',
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'finance-accounting-batch-create',
    domain: 'FinanceAccounting',
    title: '创建财务核算批次',
    method: 'POST',
    path: '/finance/accounting-batches',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      adapter_id: '',
      period_start: '2026-06-01',
      period_end: '2026-06-30',
      currency: 'CNY',
      metadata: {},
    },
  },
  {
    id: 'finance-accounting-batch-list',
    domain: 'FinanceAccounting',
    title: '财务核算批次',
    method: 'GET',
    path: '/finance/accounting-batches',
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'finance-accounting-batch-submit',
    domain: 'FinanceAccounting',
    title: '提交财务核算批次',
    method: 'POST',
    path: '/finance/accounting-batches/{id}/submit',
    pathParams: [{ name: 'id', label: '财务核算批次 ID' }],
    operationKind: 'direct',
    dangerLevel: 'medium',
  },
  {
    id: 'finance-reconciliation',
    domain: 'FinanceAccounting',
    title: '财务对账',
    method: 'GET',
    path: '/finance/reconciliation',
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'finance-settlement-create',
    domain: 'FinanceReceivables',
    title: '创建项目结算单',
    method: 'POST',
    path: '/finance/settlement-orders',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      settlement_number: '',
      project_id: null,
      customer_name: '客户名称',
      title: '项目阶段结算',
      description: '',
      currency: 'CNY',
      due_date: '2026-06-30',
      lines: [{ line_type: 'project_settlement', description: '交付结算', amount: 10000, tax_amount: 600 }],
      metadata: {},
    },
  },
  {
    id: 'finance-settlement-post',
    domain: 'FinanceReceivables',
    title: '过账项目结算单',
    method: 'POST',
    path: '/finance/settlement-orders/{id}/post',
    pathParams: [{ name: 'id', label: '结算单 ID' }],
    operationKind: 'direct',
    dangerLevel: 'medium',
  },
  {
    id: 'finance-receivable-list',
    domain: 'FinanceReceivables',
    title: '应收列表',
    method: 'GET',
    path: '/finance/receivables',
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'finance-receivable-update',
    domain: 'FinanceReceivables',
    title: '修改应收',
    method: 'PATCH',
    path: '/finance/receivables/{id}',
    pathParams: [{ name: 'id', label: '应收 ID' }],
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      customer_name: '客户名称',
      invoice_number: '',
      amount: 10000,
      tax_amount: 600,
      currency: 'CNY',
      due_date: '2026-06-30',
      metadata: {},
    },
  },
  {
    id: 'finance-receipt-create',
    domain: 'FinanceReceivables',
    title: '创建收款',
    method: 'POST',
    path: '/finance/receipts',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      receipt_number: '',
      customer_name: '客户名称',
      payment_method: 'bank_transfer',
      amount: 10000,
      currency: 'CNY',
      received_at: '2026-06-18T00:00:00Z',
      status: 'received',
      metadata: {},
    },
  },
  {
    id: 'finance-payable-list',
    domain: 'FinancePayables',
    title: '应付列表',
    method: 'GET',
    path: '/finance/payables',
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'finance-payable-update',
    domain: 'FinancePayables',
    title: '修改应付',
    method: 'PATCH',
    path: '/finance/payables/{id}',
    pathParams: [{ name: 'id', label: '应付 ID' }],
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      payable_type: 'expense',
      invoice_number: '',
      vendor_name: '供应商',
      employee_name: '',
      amount: 1000,
      tax_amount: 0,
      currency: 'CNY',
      due_date: '2026-06-30',
      metadata: {},
    },
  },
  {
    id: 'finance-payment-create',
    domain: 'FinancePayables',
    title: '创建付款',
    method: 'POST',
    path: '/finance/payments',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      payment_number: '',
      payment_method: 'bank_transfer',
      vendor_name: '供应商',
      employee_name: '',
      amount: 1000,
      currency: 'CNY',
      paid_at: '2026-06-18T00:00:00Z',
      status: 'paid',
      metadata: {},
    },
  },
  {
    id: 'inventory-partner-create',
    domain: 'Inventory',
    title: 'operation.inventory.partnerCreate',
    method: 'POST',
    path: '/inventory/partners',
    operationKind: 'direct',
    dangerLevel: 'low',
    bodyTemplate: {
      partner_type: 'supplier',
      name: 'Supplier Co',
      partner_code: '',
      email: '',
      phone: '',
      metadata: {},
    },
  },
  {
    id: 'inventory-partner-list',
    domain: 'Inventory',
    title: 'operation.inventory.partnerList',
    method: 'GET',
    path: '/inventory/partners',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'inventory-item-create',
    domain: 'Inventory',
    title: 'operation.inventory.itemCreate',
    method: 'POST',
    path: '/inventory/items',
    operationKind: 'direct',
    dangerLevel: 'low',
    bodyTemplate: {
      item_code: '',
      name: 'Material',
      item_type: 'material',
      base_uom: 'EA',
      metadata: {},
    },
  },
  {
    id: 'inventory-item-list',
    domain: 'Inventory',
    title: 'operation.inventory.itemList',
    method: 'GET',
    path: '/inventory/items',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'inventory-warehouse-create',
    domain: 'Inventory',
    title: 'operation.inventory.warehouseCreate',
    method: 'POST',
    path: '/inventory/warehouses',
    operationKind: 'direct',
    dangerLevel: 'low',
    bodyTemplate: {
      warehouse_code: '',
      name: 'Main Warehouse',
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'inventory-warehouse-list',
    domain: 'Inventory',
    title: 'operation.inventory.warehouseList',
    method: 'GET',
    path: '/inventory/warehouses',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'inventory-location-create',
    domain: 'Inventory',
    title: 'operation.inventory.locationCreate',
    method: 'POST',
    path: '/inventory/locations',
    operationKind: 'direct',
    dangerLevel: 'low',
    bodyTemplate: {
      warehouse_id: '',
      location_code: '',
      name: 'Default Location',
      status: 'active',
      metadata: {},
    },
  },
  {
    id: 'inventory-balance-list',
    domain: 'Inventory',
    title: 'operation.inventory.balanceList',
    method: 'GET',
    path: '/inventory/balances',
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'inventory-movement-create',
    domain: 'Inventory',
    title: 'operation.inventory.movementCreate',
    method: 'POST',
    path: '/inventory/movements',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      movement_type: 'purchase_receipt',
      source_type: 'manual',
      item_id: '',
      warehouse_id: '',
      quantity: 1,
      unit_cost: 0,
      currency: 'CNY',
      metadata: {},
    },
  },
  {
    id: 'inventory-movement-list',
    domain: 'Inventory',
    title: 'operation.inventory.movementList',
    method: 'GET',
    path: '/inventory/movements',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'inventory-transfer-create',
    domain: 'Inventory',
    title: 'operation.inventory.transferCreate',
    method: 'POST',
    path: '/inventory/transfers',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      transfer_number: '',
      from_warehouse_id: '',
      to_warehouse_id: '',
      status: 'draft',
      lines: [{ item_id: '', quantity: 1, unit_cost: 0 }],
      metadata: {},
    },
  },
  {
    id: 'inventory-transfer-list',
    domain: 'Inventory',
    title: 'operation.inventory.transferList',
    method: 'GET',
    path: '/inventory/transfers',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'inventory-adjustment-create',
    domain: 'Inventory',
    title: 'operation.inventory.adjustmentCreate',
    method: 'POST',
    path: '/inventory/adjustments',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      adjustment_number: '',
      warehouse_id: '',
      reason: 'cycle count correction',
      status: 'draft',
      lines: [{ item_id: '', quantity_delta: 1, unit_cost: 0 }],
      metadata: {},
    },
  },
  {
    id: 'inventory-adjustment-list',
    domain: 'Inventory',
    title: 'operation.inventory.adjustmentList',
    method: 'GET',
    path: '/inventory/adjustments',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'inventory-count-create',
    domain: 'Inventory',
    title: 'operation.inventory.countCreate',
    method: 'POST',
    path: '/inventory/counts',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      count_number: '',
      warehouse_id: '',
      status: 'draft',
      lines: [{ item_id: '', book_qty: 0, counted_qty: 1 }],
      metadata: {},
    },
  },
  {
    id: 'inventory-count-list',
    domain: 'Inventory',
    title: 'operation.inventory.countList',
    method: 'GET',
    path: '/inventory/counts',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'procurement-requisition-create',
    domain: 'Procurement',
    title: 'operation.procurement.requisitionCreate',
    method: 'POST',
    path: '/procurement/requisitions',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      title: 'Purchase requisition',
      supplier_name: 'Supplier Co',
      currency: 'CNY',
      lines: [{ item_id: '', warehouse_id: '', quantity: 1, unit_cost: 0 }],
      metadata: {},
    },
  },
  {
    id: 'procurement-requisition-list',
    domain: 'Procurement',
    title: 'operation.procurement.requisitionList',
    method: 'GET',
    path: '/procurement/requisitions',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'procurement-requisition-submit',
    domain: 'Procurement',
    title: 'operation.procurement.requisitionSubmit',
    method: 'POST',
    path: '/procurement/requisitions/{id}/submit',
    pathParams: [{ name: 'id', label: 'operation.field.purchaseRequisitionId' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
  },
  {
    id: 'procurement-requisition-approve',
    domain: 'Procurement',
    title: 'operation.procurement.requisitionApprove',
    method: 'POST',
    path: '/procurement/requisitions/{id}/approve',
    pathParams: [{ name: 'id', label: 'operation.field.purchaseRequisitionId' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
  },
  {
    id: 'procurement-order-create',
    domain: 'Procurement',
    title: 'operation.procurement.orderCreate',
    method: 'POST',
    path: '/procurement/orders',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      requisition_id: null,
      supplier_name: 'Supplier Co',
      currency: 'CNY',
      lines: [{ item_id: '', warehouse_id: '', quantity: 1, unit_cost: 0, tax_rate: 0.13 }],
      metadata: {},
    },
  },
  {
    id: 'procurement-order-list',
    domain: 'Procurement',
    title: 'operation.procurement.orderList',
    method: 'GET',
    path: '/procurement/orders',
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'procurement-order-submit',
    domain: 'Procurement',
    title: 'operation.procurement.orderSubmit',
    method: 'POST',
    path: '/procurement/orders/{id}/submit',
    pathParams: [{ name: 'id', label: 'operation.field.purchaseOrderId' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
  },
  {
    id: 'procurement-order-approve',
    domain: 'Procurement',
    title: 'operation.procurement.orderApprove',
    method: 'POST',
    path: '/procurement/orders/{id}/approve',
    pathParams: [{ name: 'id', label: 'operation.field.purchaseOrderId' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
  },
  {
    id: 'procurement-receipt-create',
    domain: 'Procurement',
    title: 'operation.procurement.receiptCreate',
    method: 'POST',
    path: '/procurement/receipts',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      supplier_name: 'Supplier Co',
      warehouse_id: '',
      currency: 'CNY',
      lines: [{ item_id: '', warehouse_id: '', quantity: 1, unit_cost: 0, tax_rate: 0.13 }],
      metadata: {},
    },
  },
  {
    id: 'procurement-receipt-list',
    domain: 'Procurement',
    title: 'operation.procurement.receiptList',
    method: 'GET',
    path: '/procurement/receipts',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'procurement-receipt-post',
    domain: 'Procurement',
    title: 'operation.procurement.receiptPost',
    method: 'POST',
    path: '/procurement/receipts/{id}/post',
    pathParams: [{ name: 'id', label: 'operation.field.purchaseReceiptId' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
  },
  {
    id: 'procurement-return-create',
    domain: 'Procurement',
    title: 'operation.procurement.returnCreate',
    method: 'POST',
    path: '/procurement/returns',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      receipt_id: null,
      supplier_name: 'Supplier Co',
      currency: 'CNY',
      lines: [{ item_id: '', warehouse_id: '', quantity: 1, unit_cost: 0, tax_rate: 0.13 }],
      metadata: {},
    },
  },
  {
    id: 'procurement-return-list',
    domain: 'Procurement',
    title: 'operation.procurement.returnList',
    method: 'GET',
    path: '/procurement/returns',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'sales-quotation-create',
    domain: 'Sales',
    title: 'operation.sales.quotationCreate',
    method: 'POST',
    path: '/sales/quotations',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      customer_name: 'Customer Co',
      currency: 'CNY',
      lines: [{ item_id: '', warehouse_id: '', quantity: 1, unit_price: 0, tax_rate: 0.13 }],
      metadata: {},
    },
  },
  {
    id: 'sales-quotation-list',
    domain: 'Sales',
    title: 'operation.sales.quotationList',
    method: 'GET',
    path: '/sales/quotations',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'sales-order-create',
    domain: 'Sales',
    title: 'operation.sales.orderCreate',
    method: 'POST',
    path: '/sales/orders',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      quotation_id: null,
      customer_name: 'Customer Co',
      currency: 'CNY',
      lines: [{ item_id: '', warehouse_id: '', quantity: 1, unit_price: 0, tax_rate: 0.13 }],
      metadata: {},
    },
  },
  {
    id: 'sales-order-list',
    domain: 'Sales',
    title: 'operation.sales.orderList',
    method: 'GET',
    path: '/sales/orders',
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'sales-order-confirm',
    domain: 'Sales',
    title: 'operation.sales.orderConfirm',
    method: 'POST',
    path: '/sales/orders/{id}/confirm',
    pathParams: [{ name: 'id', label: 'operation.field.salesOrderId' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
  },
  {
    id: 'sales-order-approve',
    domain: 'Sales',
    title: 'operation.sales.orderApprove',
    method: 'POST',
    path: '/sales/orders/{id}/approve',
    pathParams: [{ name: 'id', label: 'operation.field.salesOrderId' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
  },
  {
    id: 'sales-shipment-create',
    domain: 'Sales',
    title: 'operation.sales.shipmentCreate',
    method: 'POST',
    path: '/sales/shipments',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      customer_name: 'Customer Co',
      currency: 'CNY',
      lines: [{ item_id: '', warehouse_id: '', quantity: 1, unit_price: 0, tax_rate: 0.13 }],
      metadata: {},
    },
  },
  {
    id: 'sales-shipment-list',
    domain: 'Sales',
    title: 'operation.sales.shipmentList',
    method: 'GET',
    path: '/sales/shipments',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
  {
    id: 'sales-shipment-post',
    domain: 'Sales',
    title: 'operation.sales.shipmentPost',
    method: 'POST',
    path: '/sales/shipments/{id}/post',
    pathParams: [{ name: 'id', label: 'operation.field.salesShipmentId' }],
    operationKind: 'contextual',
    dangerLevel: 'medium',
  },
  {
    id: 'sales-return-create',
    domain: 'Sales',
    title: 'operation.sales.returnCreate',
    method: 'POST',
    path: '/sales/returns',
    operationKind: 'direct',
    dangerLevel: 'medium',
    bodyTemplate: {
      shipment_id: null,
      customer_name: 'Customer Co',
      currency: 'CNY',
      lines: [{ item_id: '', warehouse_id: '', quantity: 1, unit_price: 0, tax_rate: 0.13 }],
      metadata: {},
    },
  },
  {
    id: 'sales-return-list',
    domain: 'Sales',
    title: 'operation.sales.returnList',
    method: 'GET',
    path: '/sales/returns',
    queryParams: [{ name: 'limit', label: 'operation.field.limit', placeholder: '100' }],
    operationKind: 'direct',
    dangerLevel: 'low',
  },
]

const legacyBusinessPathPrefixes = [
  '/finance',
  '/inventory',
  '/procurement',
  '/sales',
  '/requirements',
  '/projects',
]

function isLegacyBusinessOperation(operation: ApiOperation): boolean {
  return legacyBusinessPathPrefixes.some((prefix) => operation.path === prefix || operation.path.startsWith(`${prefix}/`))
}

export const apiOperations: ApiOperation[] = allApiOperations.filter((operation) => !isLegacyBusinessOperation(operation))

export const operationDomains = Array.from(new Set(apiOperations.map((operation) => operation.domain)))
